### ISSUE TITLE
A question about reproduction

### ISSUE THREAD

**Issue by speedcell4** [jiacheng-ye/UANet#1]
Hi~

Thank you for sharing the source code.
But how to obtain the BERT-UANet results in Table 5? Could you please show me the exact command?

Thanks~

**Comment by jiacheng-ye** [comment]
Hi, we use [fastNLP](https://github.com/fastnlp/fastNLP) to combine the BERT embedding with our model. I have uploaded the related file [here](https://drive.google.com/drive/folders/1VGnsi30pdIyYEyYI3H163ifuJELOtFf9?usp=sharing). You can replace the corresponding file and run the following command:
```
CUDA_VISIBLE_DEVICES=0 python main.py --train_dir 'data/conll2003/train.txt' --dev_dir 'data/conll2003/dev.txt' --test_dir 'data/conll2003/test.txt'  --model_dir 'outs' --word_emb_dir 'data/glove.6B.100d.txt' \
--model2_layer 2 --n_head 7 --d_head 160 --threshold 0.45 --model2_dropout 0.15 --attention_dropout 0.05 --use_bert true
```
which will give you 92.06 in the test dataset. Hope this helps :)

**Comment by speedcell4** [comment]
I sent an access request form from your link

**Comment by jiacheng-ye** [comment]
Sorry, this [link](https://drive.google.com/drive/folders/1VGnsi30pdIyYEyYI3H163ifuJELOtFf9?usp=sharing) is publicly available.

**Comment by speedcell4** [comment]
Thank you~
